name: Release

on:
  release:
    types: [published]

jobs:
  test:
    uses: ./.github/workflows/ci.yml

  build-wheel:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
        with:
          python-version: '3.13'

      # Install dependencies for Poetry and the package
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install --no-root  # Install dependencies without installing the package

      # Check package version matches release tag
      - name: Check package version matches tag
        run: |
          pkgver=$(poetry run python -c "import autocorpus; print(autocorpus.__version__, end='')")


      # Build package with Poetry
      - name: Build package
        run: poetry build

      # Upload files as test artifact
      - uses: actions/upload-artifact@v4
        with:
          path: dist/*

      # Publish files as release artifacts
      - uses: softprops/action-gh-release@v2
        with:
          files: dist/*

  publish-pypi:
    needs: build-wheel
    name: Publish to PyPI
    runs-on: ubuntu-latest
    permissions:
      id-token: write

    steps:
      - name: Download wheel and sdist artifacts
        uses: actions/download-artifact@v4
        with:
          name: artifact
          path: dist

      - name: Display structure of downloaded files
        run: ls -R dist

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
